#ifndef RELOC_DATA_H
#define RELOC_DATA_H

/*
 * Selector shim — the actual symbol declarations live in
 * include/reloc_data.us.h (generated by the reloc-stub tooling). REGION_US is
 * defined by the build. This is a US-only fork; JP support was removed.
 */

#if defined(REGION_US)
#include "reloc_data.us.h"
#else
#error "reloc_data.h included without REGION_US defined (US-only fork)"
#endif

#endif /* RELOC_DATA_H */
